In [10]:
data_values = {}
with open("diabetes.txt", "r") as f:
    data = f.read()
    data = data.split()
    columns = data[0:11]
    values = data[11:]
    print(values[-1])
    pos = 0
    while pos < len(values):
        idx = pos % 11
        if columns[idx] in data_values:
            data_values[columns[idx]].append(values[pos])
        else:
            data_values[columns[idx]] = [values[pos]]
        pos += 1
        
#print(data_values)

57

In [11]:
import pandas as pd

In [12]:
df = pd.DataFrame(data_values)

In [13]:
df

,age,sex,bmi,map,tc,ldl,hdl,tch,ltg,glu,y
0,0.0380759064334241,0.0506801187398187,0.0616962065186885,0.0218723549949558,-0.0442234984244464,-0.0348207628376986,-0.0434008456520269,-0.00259226199818282,0.0199084208763183,-0.0176461251598052,151
1,-0.00188201652779104,-0.044641636506989,-0.0514740612388061,-0.0263278347173518,-0.00844872411121698,-0.0191633397482220,0.0744115640787594,-0.0394933828740919,-0.0683297436244215,-0.09220404962683,75
2,0.0852989062966783,0.0506801187398187,0.0444512133365941,-0.00567061055493425,-0.0455994512826475,-0.0341944659141195,-0.0323559322397657,-0.00259226199818282,0.00286377051894013,-0.0259303389894746,141
3,-0.0890629393522603,-0.044641636506989,-0.0115950145052127,-0.0366564467985606,0.0121905687618000,0.0249905933641021,-0.0360375700438527,0.0343088588777263,0.0226920225667445,-0.0093619113301358,206
4,0.00538306037424807,-0.044641636506989,-0.0363846922044735,0.0218723549949558,0.00393485161259318,0.0155961395104161,0.0081420836051921,-0.00259226199818282,-0.0319914449413559,-0.0466408735636482,135
...,...,...,...,...,...,...,...,...,...,...,...
437,0.0417084448844436,0.0506801187398187,0.0196615356373334,0.0597439326260547,-0.00569681839481472,-0.00256647127337676,-0.0286742944356786,-0.00259226199818282,0.0311929907028023,0.00720651632920303,178
438,-0.00551455497881059,0.0506801187398187,-0.0159062628007364,-0.067642283042187,0.0493412959332305,0.0791652772536912,-0.0286742944356786,0.0343088588777263,-0.0181182673078967,0.0444854785627154,104
439,0.0417084448844436,0.0506801187398187,-0.0159062628007364,0.0172818607481171,-0.0373437341334407,-0.0138398158977999,-0.0249926566315915,-0.0110795197996419,-0.0468794828442166,0.0154907301588724,132
440,-0.0454724779400257,-0.044641636506989,0.0390621529671896,0.00121513083253827,0.0163184273364034,0.0152829910486266,-0.0286742944356786,0.0265596234937854,0.0445283740214053,-0.0259303389894746,220
441,-0.0454724779400257,-0.044641636506989,-0.0730303027164241,-0.081413765817132,0.0837401173882587,0.0278089295202079,0.173815784789110,-0.0394933828740919,-0.00421985970694604,0.00306440941436832,57

In [15]:
df.to_csv("diabetes.csv", index=False)